// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALDa3fmTgiL0ZZAgq0VvdZL_7KepUTakY',
    appId: '1:1057725397413:web:86ae8b0d6d30144865904c',
    messagingSenderId: '1057725397413',
    projectId: 'somethin-n',
    authDomain: 'somethin-n.firebaseapp.com',
    storageBucket: 'somethin-n.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLvztbsktfiWjxTgVx9x4PfPoUwkgHYY',
    appId: '1:1057725397413:android:797dd35fb844884f65904c',
    messagingSenderId: '1057725397413',
    projectId: 'somethin-n',
    storageBucket: 'somethin-n.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTpIy3helvhmpietBuGzuH7hCKKJvxfo',
    appId: '1:1057725397413:ios:a774dc0ae2b1775c65904c',
    messagingSenderId: '1057725397413',
    projectId: 'somethin-n',
    storageBucket: 'somethin-n.firebasestorage.app',
    iosBundleId: 'com.example.myProjectFirst',
  );
}
